#!/bin/bash
# build-policy-digest.sh — Generate _digest.md index files for policy scopes.
#
# Walks the 3 policy scopes and emits a compact digest per scope:
#   1. .claude/policies/                          → .claude/policies/_digest.md
#   2. companies/*/policies/                      → companies/{co}/policies/_digest.md
#   3. repos/{public,private}/*/.claude/policies/ → {repo}/.claude/policies/_digest.md
#
# Each digest line: - [hard|soft] **{id}**: {rule one-liner (≤160 chars)}
# Digests are ordered hard-first, then soft, alphabetized within each group.
#
# Idempotent. Full rebuild across HQ typically under 15s.
# Consumed by .claude/hooks/load-policies-for-session.sh on SessionStart.
#
# Usage:
#   bash scripts/build-policy-digest.sh           # build all scopes
#   bash scripts/build-policy-digest.sh --verbose # with per-file logs

set -euo pipefail

HQ_ROOT="${HQ_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
VERBOSE=0
[ "${1:-}" = "--verbose" ] && VERBOSE=1

log() { [ $VERBOSE -eq 1 ] && echo "$@" >&2; return 0; }

# Extract a single frontmatter field. Robust against values containing colons.
# Args: <file> <field-name>
extract_field() {
  awk -v field="$2" '
    BEGIN { in_fm = 0; dashes = 0 }
    /^---$/ { dashes++; if (dashes == 1) { in_fm = 1 } else if (dashes == 2) { exit }; next }
    in_fm && $0 ~ ("^" field ": ") {
      sub("^" field ": *", "")
      gsub(/^["'"'"']|["'"'"']$/, "")
      print
      exit
    }
  ' "$1"
}

# Extract the first non-empty line under the `## Rule` heading.
# Strips markdown bold markers, caps at 160 chars for digest compactness.
extract_rule_oneliner() {
  awk '
    /^## Rule[[:space:]]*$/ { in_rule = 1; next }
    /^## / && in_rule { exit }
    in_rule && NF > 0 {
      gsub(/\*\*/, "")
      if (length($0) > 160) { $0 = substr($0, 1, 157) "..." }
      print
      exit
    }
  ' "$1"
}

# Build a digest for a single policies directory.
# Args: <policies-dir> <scope-label>
build_one_digest() {
  local dir="$1"
  local label="$2"
  local out="$dir/_digest.md"

  [ -d "$dir" ] || { log "skip (not a dir): $dir"; return 0; }

  local tmp_hard tmp_soft
  tmp_hard=$(mktemp)
  tmp_soft=$(mktemp)

  local count_hard=0 count_soft=0 count_total=0

  for f in "$dir"/*.md; do
    [ -f "$f" ] || continue
    local base
    base=$(basename "$f")
    case "$base" in
      _digest.md|example-policy.md|README.md) continue ;;
    esac

    local id enforcement rule
    id=$(extract_field "$f" id || true)
    enforcement=$(extract_field "$f" enforcement || true)
    rule=$(extract_rule_oneliner "$f" || true)

    [ -z "$id" ] && id=$(basename "$f" .md)
    [ -z "$enforcement" ] && enforcement="soft"
    [ -z "$rule" ] && rule="(no ## Rule section)"

    local line="- [${enforcement}] **${id}**: ${rule}"
    count_total=$((count_total + 1))
    if [ "$enforcement" = "hard" ]; then
      printf '%s\n' "$line" >> "$tmp_hard"
      count_hard=$((count_hard + 1))
    else
      printf '%s\n' "$line" >> "$tmp_soft"
      count_soft=$((count_soft + 1))
    fi
  done

  if [ $count_total -eq 0 ]; then
    [ -f "$out" ] && rm -f "$out"
    rm -f "$tmp_hard" "$tmp_soft"
    log "no policies in: $dir"
    return 0
  fi

  {
    printf '# Policy Digest — %s\n\n' "$label"
    printf '> Auto-generated by `scripts/build-policy-digest.sh`. Do not edit by hand.\n'
    printf '> Source: `%s`\n' "${dir#$HQ_ROOT/}"
    printf '> Policies: %d (%d hard / %d soft)\n\n' "$count_total" "$count_hard" "$count_soft"
    if [ $count_hard -gt 0 ]; then
      printf '## Hard-enforcement (%d)\n\n' "$count_hard"
      sort "$tmp_hard"
      printf '\n'
    fi
    if [ $count_soft -gt 0 ]; then
      printf '## Soft-enforcement (%d)\n\n' "$count_soft"
      sort "$tmp_soft"
      printf '\n'
    fi
  } > "$out"

  rm -f "$tmp_hard" "$tmp_soft"
  log "wrote: $out ($count_total policies)"
}

main() {
  log "HQ_ROOT=$HQ_ROOT"
  local built=0

  build_one_digest "$HQ_ROOT/.claude/policies" "Global (.claude/policies/)"
  built=$((built + 1))

  for co_dir in "$HQ_ROOT"/companies/*/; do
    [ -d "$co_dir" ] || continue
    local co
    co=$(basename "$co_dir")
    case "$co" in
      _template) continue ;;
    esac
    local pol_dir="${co_dir}policies"
    [ -d "$pol_dir" ] || continue
    build_one_digest "$pol_dir" "Company: ${co}"
    built=$((built + 1))
  done

  for scope in public private; do
    for repo_dir in "$HQ_ROOT"/repos/$scope/*/; do
      [ -d "$repo_dir" ] || continue
      local pol_dir="${repo_dir}.claude/policies"
      [ -d "$pol_dir" ] || continue
      local repo
      repo=$(basename "$repo_dir")
      build_one_digest "$pol_dir" "Repo: ${scope}/${repo}"
      built=$((built + 1))
    done
  done

  printf 'Built %d digest scope(s).\n' "$built" >&2
}

main "$@"
